### PR TITLE
[FW][ADD] l10n_uy_ux: new module

### PR DESCRIPTION
**Pull request by zaoral**
- will have everything that is not been acepted by odoo
- re add missing addenda things from odoo oficial
- methods and fields renamed
- print legal report from print menu
- button update dgi in move

Task 41816

closes #243

X-original-commit: 0a1df90f1c57059089a0051a96cfb289ca031af6

### CODE REVIEW

**Comment by roboadhoc** [comment]
This PR targets the un-managed branch ingadhoc/uruguay:18.0-17.0-t-34526-kz-v2-Fm4c-fw, it needs to be retargeted before it can be merged.

**Comment by roboadhoc** [comment]
This PR targets the un-managed branch ingadhoc/uruguay:18.0-17.0-t-34526-kz-v2-Fm4c-fw, it needs to be retargeted before it can be merged.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/uruguay/pull/262).

**Comment by mem-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
