### PR TITLE
[FW][FIX] l10n_uy_edi: e-invoice line wo product

### PR DESCRIPTION
**Pull request by mem-adhoc**
ticket: 82127
This is a manual FW of this one https://github.com/ingadhoc/uruguay/pull/253

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/uruguay/pull/255).

**Comment by zaoral** [comment]
@mem-adhoc 
Thank you for the manual FW.

Please could you:
1. add the [FW] tag to the manual fw on the title
2. make reference to the original FW in this PR
3. Close the original FW
4. Also, did you run a basic functional test?
 
Afther the changes please let me know to merge this PR
Best Regards

**Review by zaoral — APPROVED** [review]

**Comment by mem-adhoc** [comment]
@zaoral 
Hi Kathy!
I already made the changes you asked me for!
I did a functional test! in Entivox base, I let you some examples of invoices I made
[E-Ticket A0000108.pdf](https://github.com/user-attachments/files/17556872/E-Ticket.A0000108.pdf)
[E-Ticket A0000107.pdf](https://github.com/user-attachments/files/17556874/E-Ticket.A0000107.pdf)
[E-Ticket A0000106.pdf](https://github.com/user-attachments/files/17556875/E-Ticket.A0000106.pdf)

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/uruguay#256

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/uruguay#256

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/uruguay#256

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/uruguay#256

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/uruguay#256

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/uruguay#256

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/uruguay#256

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/uruguay#256

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/uruguay#256

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/uruguay#256

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/uruguay#256

**Pull request closed without merging**
