### PR TITLE
[FIX] l10n_uy_account: remove depend to account_withholding

### PR DESCRIPTION
**Pull request by zaoral**
We really do not need it and is given us trouble on migration of clients to version 17.0 (account_withholding was rename to 1l0n_ar_withholding and now depends on l10n_ar): some pure UY clients now are installing AR loc by mistake.

Ticket 41724

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/uruguay/pull/264).

**Comment by mem-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@mem-adhoc you may want to rebuild or fix this PR as it has failed CI.

**Comment by mem-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
