### PR TITLE
[FW][ADD] l10n_uy_ux: new module

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Task 41816

--

It have evething that is was in our l10n_uy_edi and l10n_uy_account that was not accepted by Odoo

- Rename module to l10n_uy_ux, his will have everything that is not been acepted by odoo
- re add missing addenda things from odoo oficial
- methods and fields renamed
- print legal report from print menu
- button update dgi in move
- create cfe template
- change addenda model, re add apply_on field
- more changes not accepted in official
- more logic for rut/ruc/cie validation
- add more things removed from core
- from odoo
- remove account_withholding module
- change fields and methods
- fix demo data
- adapt demo data adhoc

Forward-Port-Of: ingadhoc/uruguay#243

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/uruguay/pull/261).

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this PR targets 18.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro ci/runbot-oba failed on this forward-port PR

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro ci/runbot-oba failed on this forward-port PR

**Comment by zaoral** [comment]
we can not modify this FW because branch was created on ingadhoc, we cancel it and create a new manual fw https://github.com/ingadhoc/uruguay/pull/262

**Pull request closed without merging**
