### PR TITLE
[FW][FIX] l10n_uy_reports: formulario 2-181.

### PR DESCRIPTION
**Pull request by pablohmontenegro**
Ticket: 80568
Error de lógica al momento de descargar el txt del formulario 2-181 de Uruguay

This fw replaces https://github.com/ingadhoc/uruguay/pull/259
Forward-Port-Of: https://github.com/ingadhoc/uruguay/pull/250
X-original-commit: ea0bbd6f6e6eba03c5bea11e9424c3f3dfbb8ae8

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/uruguay/pull/265).

**Comment by zaoral** [comment]
* please add [FW] to the pr name
* Also reference to the original FW you are replacing https://github.com/ingadhoc/uruguay/pull/259

**Comment by zaoral** [comment]
@pablohmontenegro sorry, i forget to ping you in the last message

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
